import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "5e Campaign Manager",
  description: "Generated by create next app",
};

import { Toaster } from "@/components/ui/sonner";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster />
        <footer className="mt-20 py-8 border-t border-slate-800 text-center text-xs text-slate-500 max-w-4xl mx-auto px-4">
          <p className="mb-2">
            This project uses the System Reference Document 5.1 ("SRD 5.1" and "SRD 5.2") provided by Wizards of the Coast LLC under the terms of the Creative Commons Attribution 4.0 International License (CC-BY 4.0).
          </p>
          <p>
            "Wizards of the Coast", "Dungeons & Dragons", and their logos are trademarks of Wizards of the Coast LLC in the United States and other countries.
            This website is not affiliated with, endorsed, sponsored, or specifically approved by Wizards of the Coast LLC.
          </p>
        </footer>
      </body>
    </html>
  );
}
